version: '3'

tasks:
  conda:
    desc: "Generate conda environment files."
    cmds:
      - python -m bsos.conda_web_api conda/conda.csv
      - python -m bsos.conda_web_api conda/system.csv -v 3.12 --name-format system --no-python
