"""Tests for the installer compile system."""

import ast
import subprocess
import sys
from pathlib import Path

import pytest

from bsos.installers._compile import compile_module, discover_modules, resolve_dependencies

REPO_ROOT = Path(__file__).resolve().parents[2]

_COMPILED_MODULES = discover_modules()

# Marker the compile system writes into every standalone script it emits.
_COMPILE_MARKER = "Auto-generated by bsos compile system"

# All compiled modules import _download (directly or transitively, via _recipe),
# so __version__ is always baked into the compiled output.
_MODULES_WITH_VERSION = _COMPILED_MODULES


def test_code_dependencies_are_topologically_ordered():
    order = resolve_dependencies("code")
    # a module's intra-package deps must appear before it
    assert order.index("_env") < order.index("code")
    assert order.index("_download") < order.index("code")
    assert order[-1] == "code"


@pytest.mark.parametrize("module", _COMPILED_MODULES)
def test_compiled_is_valid_and_self_contained(module):
    text = compile_module(module)
    tree = ast.parse(text)  # must be syntactically valid
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            assert node.level == 0, f"{module}: relative import leaked into compiled output"
            assert not (node.module or "").startswith("bsos"), f"{module}: bsos import leaked: {node.module}"
        elif isinstance(node, ast.Import):
            assert not any(a.name.startswith("bsos") for a in node.names)


@pytest.mark.parametrize("module", _MODULES_WITH_VERSION)
def test_compiled_bakes_version(module):
    from bsos import __version__

    text = compile_module(module)
    assert f"__version__ = {__version__!r}" in text


@pytest.mark.parametrize("module", _COMPILED_MODULES)
def test_checked_in_script_is_up_to_date(module):
    # Compiled output keeps the module name verbatim (e.g. mamba_env.py); the
    # compile-task name swaps '_' for '-' (pixi run compile-mamba-env).
    artifact_path = REPO_ROOT / "install" / f"{module}.py"
    artifact = artifact_path.read_text()
    assert artifact == compile_module(module), (
        f"install/{module}.py is stale; regenerate with `pixi run compile`"
    )


@pytest.mark.parametrize("module", _COMPILED_MODULES)
def test_compiled_script_runs(module):
    """The shipped standalone must actually run, not merely parse.

    Parsing alone (above) never catches a def-time error — e.g. the tree-shaker
    dropping an annotation-only name like ``_download.PathLike`` while leaving
    the annotation in the signature. Invoking ``--help`` as a subprocess runs
    the whole module top level (imports, dataclass defs, RECIPE construction)
    in a real ``__main__`` and exits 0 via argparse, before any install action.
    """
    script = REPO_ROOT / "install" / f"{module}.py"
    result = subprocess.run(
        [sys.executable, str(script), "--help"],
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert result.returncode == 0, f"{script} failed to run:\n{result.stderr}"
    assert "usage:" in result.stdout
