#!/usr/bin/env python3
# Auto-generated by bsos compile system from bsos.installers.mamba_env — do not edit.
"""Conda environment installer (micromamba or mamba backend).

Creates or updates a named conda environment from an environment YAML file,
installed to ``$__OPT_ROOT/$NAME`` (default: ``system``).

``--backend`` selects the package manager (default ``micromamba``):
``micromamba`` is the standalone binary at ``$__OPT_ROOT/bin/micromamba``;
``mamba`` is the Miniforge build at ``$MAMBA_ROOT_PREFIX/bin/mamba``. Both
support ``env update --prune``, so the YAML stays authoritative on update.

The YAML file is selected by *name* + detected platform —
``<env-dir>/<name>_<conda-arch>.yml`` (e.g. ``system_linux-64.yml``) — so only
the directory (or base URL) is given; the filename is derived.  ``--env-dir``
defaults to the bundled ``conda/`` directory when running from a repo clone,
and to the canonical remote base otherwise (e.g. piped through ``curl``)::

    # bundled conda/ (repo clone), current platform:
    python3 install/mamba_env.py install --name system

    # explicit local directory:
    python3 install/mamba_env.py install --name py312 --env-dir /path/to/conda

    # explicit remote base (curl | python3 variant):
    curl -fsSL https://raw.githubusercontent.com/ickc/envoy/main/install/mamba_env.py | \
        python3 - install --name system \
        --env-dir https://raw.githubusercontent.com/ickc/envoy/main/conda"""

from __future__ import annotations

import argparse
import contextlib
import io
import os
import platform
import shutil
import subprocess
import sys
import tarfile
import tempfile
import time
import urllib.error
import urllib.request
import warnings
import zipfile
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Tuple

# Baked from the bsos package at compile time.
__version__ = '0.1.0'

# --- _download ---


_USER_AGENT = f"bsos-installer/{__version__}"
_OPEN_URL_ATTEMPTS = 3
_OPEN_URL_TIMEOUT = 60
_TRANSIENT_HTTP_STATUS = {408, 429, 500, 502, 503, 504}


def _open_url(url: str) -> Any:
    for attempt in range(_OPEN_URL_ATTEMPTS):
        req = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT})
        try:
            return urllib.request.urlopen(req, timeout=_OPEN_URL_TIMEOUT)  # noqa: S310 — URL is from our dispatch table
        except urllib.error.HTTPError as exc:
            if exc.code not in _TRANSIENT_HTTP_STATUS or attempt == _OPEN_URL_ATTEMPTS - 1:
                raise
        except (urllib.error.URLError, TimeoutError):
            # URLError covers connection-phase failures; a read timeout while
            # reading the response (e.g. following the /releases/latest
            # redirect) surfaces as a bare TimeoutError, not wrapped in
            # URLError. Both are transient and worth retrying.
            if attempt == _OPEN_URL_ATTEMPTS - 1:
                raise
        time.sleep(2**attempt)
    raise RuntimeError(f"Could not open URL after retries: {url}")


def download_file(url: str, dest: PathLike) -> None:
    """Download *url* to a local file at *dest*."""
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{dest.name}.", suffix=".tmp", dir=dest.parent)
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "wb") as f, _open_url(url) as resp:
            shutil.copyfileobj(resp, f)
        tmp.replace(dest)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise


# --- _env ---


# Inherited env vars that are safe/useful to pass to installer subprocesses.
_INHERIT_KEYS = (
    "HOME",
    "USER",
    "LOGNAME",
    "TERM",
    "PATH",
    "LANG",
    "LC_ALL",
    "TMPDIR",
    "SHELL",
    "SSH_AUTH_SOCK",
    "HTTP_PROXY",
    "HTTPS_PROXY",
    "NO_PROXY",
    "ALL_PROXY",
    "http_proxy",
    "https_proxy",
    "no_proxy",
    "all_proxy",
    "GITHUB_TOKEN",
    "GH_TOKEN",
)


def detect_platform() -> Tuple[str, str]:
    """Detect OS and architecture, matching ``uname -sm`` output."""
    return platform.system(), platform.machine()


def platform_key() -> str:
    """Return ``<ostype>-<arch>`` for use in URL/archive dispatch tables."""
    ostype, arch = detect_platform()
    return f"{ostype}-{arch}"


class EnvConfig:
    """Compute envoy-managed paths, respecting pre-existing env vars.

    Path-like attributes are :class:`pathlib.Path`; the env-var mapping
    (:meth:`as_dict`) stringifies them.  An empty pre-existing value is
    treated as unset, matching the shell ``${VAR:-default}`` semantics.
    """

    def __init__(self, environ: Optional[Dict[str, str]] = None) -> None:
        env = dict(environ) if environ is not None else dict(os.environ)

        self.ostype, self.arch = detect_platform()
        self.home = Path(env.get("HOME") or Path.home())

        appdir = env.get("__APPDIR", "")
        self.local_root = Path(env.get("__LOCAL_ROOT") or (f"{appdir}/local" if appdir else self.home / ".local"))
        self.opt_root = Path(env.get("__OPT_ROOT") or self.local_root / "opt" / f"{self.ostype}-{self.arch}")

        self.mamba_root_prefix = Path(env.get("MAMBA_ROOT_PREFIX") or self.opt_root / "micromamba")
        self.pixi_home = Path(env.get("PIXI_HOME") or self.opt_root / "pixi")
        self.zim_home = Path(env.get("ZIM_HOME") or self.home / ".zim")
        self.lmod_init = Path(env.get("__LMOD_INIT") or self.opt_root / "system" / "lmod" / "lmod" / "init")

        self.xdg_config_home = Path(env.get("XDG_CONFIG_HOME") or self.home / ".config")
        self.xdg_data_home = Path(env.get("XDG_DATA_HOME") or self.local_root / "share")
        self.xdg_state_home = Path(env.get("XDG_STATE_HOME") or self.local_root / "state")
        self.xdg_cache_home = Path(env.get("XDG_CACHE_HOME") or self.home / ".cache")

        self.bin_dir = self.opt_root / "bin"

    def as_dict(self) -> Dict[str, str]:
        """All envoy-managed vars as a flat ``str``-valued dict."""
        return {
            "__OSTYPE": self.ostype,
            "__ARCH": self.arch,
            "__LOCAL_ROOT": str(self.local_root),
            "__OPT_ROOT": str(self.opt_root),
            "MAMBA_ROOT_PREFIX": str(self.mamba_root_prefix),
            "PIXI_HOME": str(self.pixi_home),
            "ZIM_HOME": str(self.zim_home),
            "__LMOD_INIT": str(self.lmod_init),
            "XDG_CONFIG_HOME": str(self.xdg_config_home),
            "XDG_DATA_HOME": str(self.xdg_data_home),
            "XDG_STATE_HOME": str(self.xdg_state_home),
            "XDG_CACHE_HOME": str(self.xdg_cache_home),
        }

    def subprocess_env(self) -> Dict[str, str]:
        """Controlled environment for installer subprocesses.

        A minimal base of inherited vars plus all envoy-managed vars, so
        child processes don't inherit unrelated env state.
        """
        env = {key: os.environ[key] for key in _INHERIT_KEYS if key in os.environ}
        env.update(self.as_dict())
        return env


# --- _subprocess ---


def run(
    cmd: List[str],
    env: Optional[Dict[str, str]] = None,
    check: bool = True,
    **kwargs: Any,
) -> "subprocess.CompletedProcess[Any]":
    """Run *cmd* with an explicit environment.

    Pass *env* from :meth:`EnvConfig.subprocess_env` to isolate the child
    from the caller's full environment.  *check* defaults to ``True``;
    pass ``check=False`` when the caller wants to inspect ``returncode``.
    """
    return subprocess.run(cmd, env=env, check=check, **kwargs)

# --- mamba_env ---


# platform_key() -> conda subdir token (this installer's analog of Artifact.targets).
_CONDA_ARCH = {
    "Darwin-arm64": "osx-arm64",
    "Darwin-x86_64": "osx-64",
    "Linux-x86_64": "linux-64",
    "Linux-aarch64": "linux-aarch64",
    "Linux-ppc64le": "linux-ppc64le",
}

# Canonical remote base, used when no bundled conda/ dir is found (e.g. curl | python3).
_REMOTE_ENV_DIR = "https://raw.githubusercontent.com/ickc/envoy/main/conda"


def _conda_arch() -> str:
    """Return the conda arch token for this platform, exiting 1 if unsupported."""
    key = platform_key()
    arch = _CONDA_ARCH.get(key)
    if arch is None:
        print(f"Unsupported platform: {key}", file=sys.stderr)
        sys.exit(1)
    return arch


def _find_bundled_conda_dir() -> Optional[Path]:
    """Locate the bundled ``conda/`` directory near this script.

    Works both as a source module (``src/bsos/installers/``) and as a compiled
    standalone script (``install/mamba_env.py`` — the repo root is one level up).
    """
    if "__file__" not in globals():
        return None
    script_dir = Path(__file__).resolve().parent
    for root in [script_dir, *list(script_dir.parents)[:4]]:
        candidate = root / "conda"
        if candidate.is_dir():
            return candidate
    return None


def _default_env_dir() -> str:
    """Bundled ``conda/`` dir when running from a clone, else the remote base."""
    local = _find_bundled_conda_dir()
    return str(local) if local is not None else _REMOTE_ENV_DIR


_BACKENDS = ("micromamba", "mamba")
_DEFAULT_BACKEND = "micromamba"


def _backend_bin(backend: str, env: EnvConfig) -> Path:
    """Path to the package-manager binary for *backend*.

    micromamba is a standalone binary under ``$__OPT_ROOT/bin``; mamba lives in
    the Miniforge tree at ``$MAMBA_ROOT_PREFIX/bin``.
    """
    if backend == "micromamba":
        return env.bin_dir / "micromamba"
    return env.mamba_root_prefix / "bin" / "mamba"


def _require_backend(backend: str, env: EnvConfig) -> Optional[Path]:
    """Return the backend binary path, or print an error and return ``None``."""
    tool = _backend_bin(backend, env)
    if not tool.exists():
        print(
            f"{backend} not found at {tool}; install it first (run install/{backend}.py install)",
            file=sys.stderr,
        )
        return None
    return tool


@contextlib.contextmanager
def _env_yaml(base: str, filename: str) -> Iterator[Path]:
    """Yield a local path to ``<base>/<filename>``.

    *base* is a local directory or an ``http(s)://`` base URL; a remote file is
    downloaded into a temp directory that is removed on exit.
    """
    if base.startswith(("http://", "https://")):
        tmp = Path(tempfile.mkdtemp(prefix="bsos-env-"))
        try:
            dest = tmp / filename
            download_file(f"{base.rstrip('/')}/{filename}", dest)
            yield dest
        finally:
            shutil.rmtree(tmp, ignore_errors=True)
    else:
        path = Path(base) / filename
        if not path.is_file():
            print(f"Env file not found: {path}", file=sys.stderr)
            sys.exit(1)
        yield path


def install(
    name: str = "system",
    env_dir: Optional[str] = None,
    env: Optional[EnvConfig] = None,
    force: bool = False,
    backend: str = _DEFAULT_BACKEND,
) -> None:
    """Create a named conda environment, or skip if it already exists.

    With *force=True* (the ``update`` action), an existing env is updated via
    ``env update --prune``; a missing env is created as normal. *backend*
    selects the package manager (``micromamba`` or ``mamba``).

    The env YAML is ``<env_dir>/<name>_<conda-arch>.yml``; *env_dir* may be a
    local directory or an ``http(s)://`` base URL (default: the bundled
    ``conda/`` dir, else the canonical remote base).
    """
    env = env or EnvConfig()

    tool = _require_backend(backend, env)
    if tool is None:
        sys.exit(1)

    prefix = env.opt_root / name
    if not force and prefix.exists():
        print(f"Conda env {name!r} already exists at {prefix}; run 'update' to refresh")
        return

    filename = f"{name}_{_conda_arch()}.yml"
    base = env_dir if env_dir is not None else _default_env_dir()
    with _env_yaml(base, filename) as spec:
        if prefix.exists():
            print(f"Updating conda env {name!r} at {prefix} via {backend} ...")
            argv = [str(tool), "env", "update", "-y", "-p", str(prefix), "-f", str(spec), "--prune"]
        elif backend == "micromamba":
            print(f"Creating conda env {name!r} at {prefix} via micromamba ...")
            argv = [str(tool), "create", "-y", "-p", str(prefix), "-f", str(spec)]
        else:
            print(f"Creating conda env {name!r} at {prefix} via mamba ...")
            argv = [str(tool), "env", "create", "-y", "-p", str(prefix), "-f", str(spec)]
        run(argv, env=env.subprocess_env())
    print(f"Conda env {name!r} ready at {prefix}")


def uninstall(name: str = "system", env: Optional[EnvConfig] = None) -> None:
    env = env or EnvConfig()
    prefix = env.opt_root / name
    if prefix.exists():
        shutil.rmtree(prefix)
        print(f"Removed conda env at {prefix}")
    else:
        print(f"{prefix} not found", file=sys.stderr)


def test_install(name: str = "system", env: Optional[EnvConfig] = None, backend: str = _DEFAULT_BACKEND) -> int:
    """Validate that the named conda env exists on the current platform.

    Skips cleanly (exit 0) on unsupported platforms.  Fails (exit 1) if the
    chosen *backend* is absent — a missing prerequisite, not a platform limit.
    """
    env = env or EnvConfig()
    key = platform_key()
    if key not in _CONDA_ARCH:
        print(f"Platform {key} unsupported by mamba_env installer; skipping", file=sys.stderr)
        return 0
    tool = _require_backend(backend, env)
    if tool is None:
        return 1
    prefix = env.opt_root / name
    if not prefix.exists():
        print(f"Conda env {name!r} not found at {prefix}; run install first", file=sys.stderr)
        return 1
    result = run([str(tool), "env", "list"], env=env.subprocess_env(), check=False)
    return result.returncode


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "action",
        choices=["install", "update", "reinstall", "uninstall", "test"],
        help="install: create env if absent, skip if already present; "
        "update: force env update even if env exists; "
        "reinstall: remove env then create fresh; "
        "uninstall: remove env; test: validate",
    )
    parser.add_argument(
        "--name",
        default="system",
        help="conda env name and prefix subdirectory (default: system)",
    )
    parser.add_argument(
        "--env-dir",
        default=None,
        metavar="PATH_OR_URL",
        help="directory or base URL holding <name>_<arch>.yml "
        "(default: bundled conda/, else the canonical remote base)",
    )
    parser.add_argument(
        "--backend",
        choices=_BACKENDS,
        default=_DEFAULT_BACKEND,
        help=f"package manager driving env create/update (default: {_DEFAULT_BACKEND})",
    )
    args = parser.parse_args()
    env = EnvConfig()
    if args.action == "install":
        install(args.name, args.env_dir, env, backend=args.backend)
    elif args.action == "update":
        install(args.name, args.env_dir, env, force=True, backend=args.backend)
    elif args.action == "reinstall":
        uninstall(args.name, env)
        install(args.name, args.env_dir, env, backend=args.backend)
    elif args.action == "uninstall":
        uninstall(args.name, env)
    else:
        sys.exit(test_install(args.name, env, backend=args.backend))


if __name__ == "__main__":
    main()
