#!/usr/bin/env python3
# Auto-generated by bsos compile system from bsos.installers.mamba — do not edit.
"""Miniforge3 (mamba) installer.

Downloads and runs the official Miniforge3 shell installer for the current
platform.  Performs a fresh install or an in-place update depending on
whether ``$MAMBA_ROOT_PREFIX`` already exists."""

import argparse
import io
import os
import platform
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
import zipfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

# Baked from the bsos package at compile time.
__version__ = '0.1.0'

# --- _download ---


_USER_AGENT = f"bsos-installer/{__version__}"

PathLike = Union[str, Path]


def _open_url(url: str):
    req = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT})
    return urllib.request.urlopen(req)  # noqa: S310 — URL is from our own dispatch table


def download_file(url: str, dest: PathLike) -> None:
    """Download *url* to a local file at *dest*."""
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    with _open_url(url) as resp, dest.open("wb") as f:
        shutil.copyfileobj(resp, f)


# --- _env ---


# Inherited env vars that are safe/useful to pass to installer subprocesses.
_INHERIT_KEYS = (
    "HOME",
    "USER",
    "LOGNAME",
    "TERM",
    "PATH",
    "LANG",
    "LC_ALL",
    "TMPDIR",
    "SHELL",
    "SSH_AUTH_SOCK",
)


def detect_platform() -> Tuple[str, str]:
    """Detect OS and architecture, matching ``uname -sm`` output."""
    return platform.system(), platform.machine()


def platform_key() -> str:
    """Return ``<ostype>-<arch>`` for use in URL/archive dispatch tables."""
    ostype, arch = detect_platform()
    return f"{ostype}-{arch}"


class EnvConfig:
    """Compute envoy-managed paths, respecting pre-existing env vars.

    Path-like attributes are :class:`pathlib.Path`; the env-var mapping
    (:meth:`as_dict`) stringifies them.  An empty pre-existing value is
    treated as unset, matching the shell ``${VAR:-default}`` semantics.
    """

    def __init__(self, environ: Optional[Dict[str, str]] = None) -> None:
        env = dict(environ) if environ is not None else dict(os.environ)

        self.ostype, self.arch = detect_platform()
        self.home = Path(env.get("HOME") or Path.home())

        appdir = env.get("__APPDIR", "")
        self.local_root = Path(
            env.get("__LOCAL_ROOT")
            or (f"{appdir}/local" if appdir else self.home / ".local")
        )
        self.opt_root = Path(
            env.get("__OPT_ROOT") or self.local_root / "opt" / f"{self.ostype}-{self.arch}"
        )

        self.mamba_root_prefix = Path(env.get("MAMBA_ROOT_PREFIX") or self.opt_root / "miniforge3")
        self.pixi_home = Path(env.get("PIXI_HOME") or self.opt_root / "pixi")
        self.zim_home = Path(env.get("ZIM_HOME") or self.home / ".zim")

        self.xdg_config_home = Path(env.get("XDG_CONFIG_HOME") or self.home / ".config")
        self.xdg_data_home = Path(env.get("XDG_DATA_HOME") or self.local_root / "share")
        self.xdg_state_home = Path(env.get("XDG_STATE_HOME") or self.local_root / "state")
        self.xdg_cache_home = Path(env.get("XDG_CACHE_HOME") or self.home / ".cache")

        self.bin_dir = self.opt_root / "bin"

    def as_dict(self) -> Dict[str, str]:
        """All envoy-managed vars as a flat ``str``-valued dict."""
        return {
            "__OSTYPE": self.ostype,
            "__ARCH": self.arch,
            "__LOCAL_ROOT": str(self.local_root),
            "__OPT_ROOT": str(self.opt_root),
            "MAMBA_ROOT_PREFIX": str(self.mamba_root_prefix),
            "PIXI_HOME": str(self.pixi_home),
            "ZIM_HOME": str(self.zim_home),
            "XDG_CONFIG_HOME": str(self.xdg_config_home),
            "XDG_DATA_HOME": str(self.xdg_data_home),
            "XDG_STATE_HOME": str(self.xdg_state_home),
            "XDG_CACHE_HOME": str(self.xdg_cache_home),
        }

    def subprocess_env(self) -> Dict[str, str]:
        """Controlled environment for installer subprocesses.

        A minimal base of inherited vars plus all envoy-managed vars, so
        child processes don't inherit unrelated env state.
        """
        env = {key: os.environ[key] for key in _INHERIT_KEYS if key in os.environ}
        env.update(self.as_dict())
        return env


# --- _subprocess ---


def run(
    cmd: List[str],
    env: Optional[Dict[str, str]] = None,
    check: bool = True,
    **kwargs: object,
) -> "subprocess.CompletedProcess":
    """Run *cmd* with an explicit environment.

    Pass *env* from :meth:`EnvConfig.subprocess_env` to isolate the child
    from the caller's full environment.  *check* defaults to ``True``;
    pass ``check=False`` when the caller wants to inspect ``returncode``.
    """
    return subprocess.run(cmd, env=env, check=check, **kwargs)

# --- mamba ---


_URLS = {
    "Darwin-arm64": "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Darwin-arm64.sh",
    "Darwin-x86_64": "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Darwin-x86_64.sh",
    "Linux-x86_64": "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh",
    "Linux-aarch64": "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh",
    "Linux-ppc64le": "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-ppc64le.sh",
}


def install(env: Optional[EnvConfig] = None) -> None:
    env = env or EnvConfig()
    key = platform_key()
    url = _URLS.get(key)
    if url is None:
        print(f"Unsupported platform: {key}", file=sys.stderr)
        sys.exit(1)

    tmp = Path(tempfile.mkdtemp(prefix="bsos-mamba-"))
    try:
        installer = tmp / "Miniforge3.sh"
        download_file(url, installer)
        installer.chmod(installer.stat().st_mode | stat.S_IEXEC)

        update = (env.mamba_root_prefix / "etc" / "profile.d" / "conda.sh").exists()
        flag = "-ubsp" if update else "-fbsp"
        action = "Updating" if update else "Installing"
        print(f"{action} mamba to {env.mamba_root_prefix} ...")
        run([str(installer), flag, str(env.mamba_root_prefix)], env=env.subprocess_env())
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print(f"Installed mamba to {env.mamba_root_prefix}")


def uninstall(env: Optional[EnvConfig] = None) -> None:
    env = env or EnvConfig()
    if env.mamba_root_prefix.exists():
        shutil.rmtree(env.mamba_root_prefix)
        print(f"Removed {env.mamba_root_prefix}")
    else:
        print(f"{env.mamba_root_prefix} not found", file=sys.stderr)


def test_install(env: Optional[EnvConfig] = None) -> int:
    """Validate the mamba install on the current platform.

    Skips cleanly (exit 0) on unsupported platforms.
    """
    env = env or EnvConfig()
    key = platform_key()
    if key not in _URLS:
        print(f"Platform {key} unsupported by mamba installer; skipping", file=sys.stderr)
        return 0
    mamba_bin = env.mamba_root_prefix / "bin" / "mamba"
    if not mamba_bin.exists():
        print(f"{mamba_bin} not found; run install first", file=sys.stderr)
        return 1
    result = run([str(mamba_bin), "--version"], env=env.subprocess_env(), check=False)
    return result.returncode


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "action",
        choices=["install", "uninstall", "test"],
        help="install/uninstall Miniforge3, or test validates an install "
        "(skips cleanly if the platform is unsupported)",
    )
    args = parser.parse_args()
    env = EnvConfig()
    if args.action == "install":
        install(env)
    elif args.action == "uninstall":
        uninstall(env)
    else:
        sys.exit(test_install(env))


if __name__ == "__main__":
    main()
