#!/usr/bin/env python3
# Auto-generated by bsos compile system from bsos.installers.pixi — do not edit.
"""Pixi installer.

Downloads the latest pixi binary from GitHub releases and installs it to
``$PIXI_HOME/bin/pixi``."""

from __future__ import annotations

import argparse
import io
import os
import platform
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
import time
import urllib.error
import urllib.request
import warnings
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple, Union

# Baked from the bsos package at compile time.
__version__ = '0.1.0'

# --- _download ---


_USER_AGENT = f"bsos-installer/{__version__}"
_OPEN_URL_ATTEMPTS = 3
_OPEN_URL_TIMEOUT = 60
_TRANSIENT_HTTP_STATUS = {408, 429, 500, 502, 503, 504}


def _open_url(url: str) -> Any:
    for attempt in range(_OPEN_URL_ATTEMPTS):
        req = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT})
        try:
            return urllib.request.urlopen(req, timeout=_OPEN_URL_TIMEOUT)  # noqa: S310 — URL is from our dispatch table
        except urllib.error.HTTPError as exc:
            if exc.code not in _TRANSIENT_HTTP_STATUS or attempt == _OPEN_URL_ATTEMPTS - 1:
                raise
        except (urllib.error.URLError, TimeoutError):
            # URLError covers connection-phase failures; a read timeout while
            # reading the response (e.g. following the /releases/latest
            # redirect) surfaces as a bare TimeoutError, not wrapped in
            # URLError. Both are transient and worth retrying.
            if attempt == _OPEN_URL_ATTEMPTS - 1:
                raise
        time.sleep(2**attempt)
    raise RuntimeError(f"Could not open URL after retries: {url}")


def _extract_tar(data: io.BytesIO, dest_dir: Path) -> None:
    with tarfile.open(fileobj=data, mode="r:*") as tar:
        # filter="data" (PEP 706) rejects absolute/parent paths and strips
        # unsafe mode bits (CVE-2007-4559). Use an explicit validator on
        # Pythons that predate it instead of the unsafe legacy extractall path.
        try:
            tar.extractall(dest_dir, filter="data")
        except TypeError:
            _extract_tar_legacy_safe(tar, dest_dir)


def _is_relative_to(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


def _extract_tar_legacy_safe(tar: tarfile.TarFile, dest_dir: Path) -> None:
    """Extract tar members safely on Pythons without tarfile data filters."""
    root = dest_dir.resolve()
    members = []
    for member in tar.getmembers():
        target = (dest_dir / member.name).resolve()
        if not _is_relative_to(target, root):
            raise RuntimeError(f"Unsafe tar member path: {member.name!r}")
        if member.isdev():
            raise RuntimeError(f"Unsafe tar member type: {member.name!r}")
        if member.issym() or member.islnk():
            link = Path(member.linkname)
            link_target = (target.parent / link).resolve() if not link.is_absolute() else link.resolve()
            if not _is_relative_to(link_target, root):
                raise RuntimeError(f"Unsafe tar link target: {member.name!r} -> {member.linkname!r}")
        member.mode &= 0o755
        members.append(member)
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=DeprecationWarning)
        tar.extractall(dest_dir, members=members)


def download_file(url: str, dest: PathLike) -> None:
    """Download *url* to a local file at *dest*."""
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{dest.name}.", suffix=".tmp", dir=dest.parent)
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "wb") as f, _open_url(url) as resp:
            shutil.copyfileobj(resp, f)
        tmp.replace(dest)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise


def download_and_extract_tar(url: str, dest_dir: PathLike) -> None:
    """Download a tar archive and extract into *dest_dir*."""
    dest_dir = Path(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)
    with _open_url(url) as resp:
        data = io.BytesIO(resp.read())
    _extract_tar(data, dest_dir)


def download_and_extract_zip(url: str, dest_dir: PathLike) -> None:
    """Download a zip archive and extract into *dest_dir*."""
    dest_dir = Path(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)
    with _open_url(url) as resp:
        data = io.BytesIO(resp.read())
    with zipfile.ZipFile(data) as zf:
        zf.extractall(dest_dir)


def resolve_latest_github_tag(owner: str, repo: str) -> str:
    """Return the latest release tag for a GitHub repo without calling the GitHub API.

    Follows the /releases/latest redirect URL; the final URL ends with /tag/<tagname>.
    Avoids the GitHub API (60 req/hour unauthenticated limit).
    """
    url = f"https://github.com/{owner}/{repo}/releases/latest"
    with _open_url(url) as resp:
        final_url = str(resp.url).rstrip("/")
    if "/tag/" not in final_url:
        raise RuntimeError(
            f"Could not resolve latest release tag for {owner}/{repo}: "
            f"{url} ended at {final_url!r}, not a release tag URL"
        )
    tag = final_url.rsplit("/tag/", 1)[1].split("/", 1)[0]
    if not tag or tag in {"latest", "releases"}:
        raise RuntimeError(f"Could not resolve latest release tag for {owner}/{repo}")
    return tag


def download_to_tempdir(url: str, extract: str = "tar") -> Path:
    """Download and extract an archive into a fresh temp directory.

    Returns the temp directory path (caller is responsible for cleanup).
    *extract* is ``"tar"`` or ``"zip"``.
    """
    tmp = Path(tempfile.mkdtemp(prefix="bsos-"))
    try:
        if extract == "tar":
            download_and_extract_tar(url, tmp)
        elif extract == "zip":
            download_and_extract_zip(url, tmp)
        else:
            raise ValueError(f"Unknown extract format: {extract}")
        return tmp
    except Exception:
        shutil.rmtree(tmp, ignore_errors=True)
        raise

# --- _env ---


# Inherited env vars that are safe/useful to pass to installer subprocesses.
_INHERIT_KEYS = (
    "HOME",
    "USER",
    "LOGNAME",
    "TERM",
    "PATH",
    "LANG",
    "LC_ALL",
    "TMPDIR",
    "SHELL",
    "SSH_AUTH_SOCK",
    "HTTP_PROXY",
    "HTTPS_PROXY",
    "NO_PROXY",
    "ALL_PROXY",
    "http_proxy",
    "https_proxy",
    "no_proxy",
    "all_proxy",
    "GITHUB_TOKEN",
    "GH_TOKEN",
)


def detect_platform() -> Tuple[str, str]:
    """Detect OS and architecture, matching ``uname -sm`` output."""
    return platform.system(), platform.machine()


def platform_key() -> str:
    """Return ``<ostype>-<arch>`` for use in URL/archive dispatch tables."""
    ostype, arch = detect_platform()
    return f"{ostype}-{arch}"


class EnvConfig:
    """Compute envoy-managed paths, respecting pre-existing env vars.

    Path-like attributes are :class:`pathlib.Path`; the env-var mapping
    (:meth:`as_dict`) stringifies them.  An empty pre-existing value is
    treated as unset, matching the shell ``${VAR:-default}`` semantics.
    """

    def __init__(self, environ: Optional[Dict[str, str]] = None) -> None:
        env = dict(environ) if environ is not None else dict(os.environ)

        self.ostype, self.arch = detect_platform()
        self.home = Path(env.get("HOME") or Path.home())

        appdir = env.get("__APPDIR", "")
        self.local_root = Path(env.get("__LOCAL_ROOT") or (f"{appdir}/local" if appdir else self.home / ".local"))
        self.opt_root = Path(env.get("__OPT_ROOT") or self.local_root / "opt" / f"{self.ostype}-{self.arch}")

        self.mamba_root_prefix = Path(env.get("MAMBA_ROOT_PREFIX") or self.opt_root / "miniforge3")
        self.pixi_home = Path(env.get("PIXI_HOME") or self.opt_root / "pixi")
        self.zim_home = Path(env.get("ZIM_HOME") or self.home / ".zim")

        self.xdg_config_home = Path(env.get("XDG_CONFIG_HOME") or self.home / ".config")
        self.xdg_data_home = Path(env.get("XDG_DATA_HOME") or self.local_root / "share")
        self.xdg_state_home = Path(env.get("XDG_STATE_HOME") or self.local_root / "state")
        self.xdg_cache_home = Path(env.get("XDG_CACHE_HOME") or self.home / ".cache")

        self.bin_dir = self.opt_root / "bin"

    def as_dict(self) -> Dict[str, str]:
        """All envoy-managed vars as a flat ``str``-valued dict."""
        return {
            "__OSTYPE": self.ostype,
            "__ARCH": self.arch,
            "__LOCAL_ROOT": str(self.local_root),
            "__OPT_ROOT": str(self.opt_root),
            "MAMBA_ROOT_PREFIX": str(self.mamba_root_prefix),
            "PIXI_HOME": str(self.pixi_home),
            "ZIM_HOME": str(self.zim_home),
            "XDG_CONFIG_HOME": str(self.xdg_config_home),
            "XDG_DATA_HOME": str(self.xdg_data_home),
            "XDG_STATE_HOME": str(self.xdg_state_home),
            "XDG_CACHE_HOME": str(self.xdg_cache_home),
        }

    def subprocess_env(self) -> Dict[str, str]:
        """Controlled environment for installer subprocesses.

        A minimal base of inherited vars plus all envoy-managed vars, so
        child processes don't inherit unrelated env state.
        """
        env = {key: os.environ[key] for key in _INHERIT_KEYS if key in os.environ}
        env.update(self.as_dict())
        return env


# --- _subprocess ---


def run(
    cmd: List[str],
    env: Optional[Dict[str, str]] = None,
    check: bool = True,
    **kwargs: object,
) -> "subprocess.CompletedProcess":
    """Run *cmd* with an explicit environment.

    Pass *env* from :meth:`EnvConfig.subprocess_env` to isolate the child
    from the caller's full environment.  *check* defaults to ``True``;
    pass ``check=False`` when the caller wants to inspect ``returncode``.
    """
    return subprocess.run(cmd, env=env, check=check, **kwargs)

# --- _recipe ---


# ─────────────────────────────────────────────────────────────────────────────
# Stage 1 — version: how to fill ``{version}`` and ``{tag}`` in a download URL.
# ─────────────────────────────────────────────────────────────────────────────
class VersionSpec:
    """Strategy for resolving the ``{version}`` and ``{tag}`` tokens of a download URL.

    ``{tag}`` is the full git tag as released (e.g. ``v1.2.3``, ``rust-v0.135.0``,
    ``26.3.2-2``).  ``{version}`` is the bare version string — the tag with any
    leading ``v`` stripped (e.g. ``1.2.3``).  Use ``{tag}`` in the URL *path*
    (it always matches the release URL exactly) and ``{version}`` in filenames
    or archive members where the convention omits the ``v``.
    """

    def resolve_both(self, override: Optional[str] = None) -> "tuple[str, str]":
        """Return ``(tag, version)`` — a single call to avoid redundant network requests."""
        raise NotImplementedError

    def resolve(self, override: Optional[str] = None) -> str:
        """Return ``{version}`` — the bare version string (leading ``v`` stripped if present)."""
        return self.resolve_both(override)[1]


@dataclass
class Latest(VersionSpec):
    """No version lookup — the URL uses the ``/releases/latest/download/`` redirect.

    Only for non-GitHub-releases URLs that have no ``{version}`` slot.  The
    ``--version`` flag is rejected at the ``run_cli`` level before this is reached.
    """

    def resolve_both(self, override: Optional[str] = None) -> "tuple[str, str]":
        return "latest", "latest"


@dataclass
class GitHubRedirect(VersionSpec):
    """Resolve the latest release tag via the ``/releases/latest`` redirect.

    Never calls the GitHub API (rate-limited at 60 req/hour unauthenticated).
    ``{tag}`` in a URL template always resolves to the full git tag as released,
    so it works for any tag format (``v1.2.3``, ``26.3.2-2``, ``rust-v0.135.0``).
    ``{version}`` strips a leading ``v`` when *strip_v* is ``True`` — useful for
    filenames or archive members where the convention omits the ``v``.

    ``--version`` overrides the auto-resolved tag; *strip_v* is applied to the
    override identically to the resolved tag, so ``{version}`` is consistent
    whether the user supplies the ``v`` or not.
    """

    owner: str
    repo: str
    strip_v: bool = True

    def resolve_both(self, override: Optional[str] = None) -> "tuple[str, str]":
        tag = override if override is not None else resolve_latest_github_tag(self.owner, self.repo)
        version = tag.lstrip("v") if self.strip_v else tag
        return tag, version


# ─────────────────────────────────────────────────────────────────────────────
# Stage 2 — archive kind and destination.
# ─────────────────────────────────────────────────────────────────────────────
@dataclass(frozen=True)
class Archive:
    """An archive format: its filename extension and its extractor kind.

    Frozen (immutable, hashable) so the ``RAW`` constant is usable as the
    ``Artifact.archive`` field default — these are shared value constants.
    """

    ext: str
    kind: Optional[str]  # "tar" | "zip" | None (raw, not an archive)


TAR = Archive("tar.gz", "tar")
ZIP = Archive("zip", "zip")
RAW = Archive("", None)


@dataclass
class Dest:
    """A destination: an :class:`EnvConfig` directory attribute plus a relative path."""

    area: str  # an EnvConfig attribute name, e.g. "bin_dir", "pixi_home"
    rel: str = ""

    def path(self, env: EnvConfig) -> Path:
        base: Path = getattr(env, self.area)
        return base / self.rel if self.rel else base

    @classmethod
    def bin(cls, name: str) -> "Dest":
        """Shorthand for ``$__OPT_ROOT/bin/<name>``."""
        return cls("bin_dir", name)


@dataclass
class Artifact:
    """One download that results in one placed file (or one run script).

    ``url_template`` may reference ``{target}`` (the per-platform token),
    ``{tag}`` (the full git tag as released, e.g. ``v1.2.3``), ``{version}``
    (the bare version — leading ``v`` stripped when *strip_v* is set on the
    :class:`VersionSpec`) and ``{ext}`` (the resolved archive extension).
    ``member`` is the path of the wanted file *inside* the extracted archive
    (templated the same way); ``None`` means the download itself is the file.
    """

    url_template: str
    dest: Dest
    targets: Optional[Dict[str, str]] = None  # platform_key -> token; None = platform-independent
    version: VersionSpec = field(default_factory=Latest)
    archive: Union[Archive, Dict[str, Archive]] = RAW  # scalar, or per-platform mapping
    member: Optional[str] = None
    executable: bool = True
    action: Optional["RunScript"] = None  # forward ref keeps RunScript out of place-only scripts


# ─────────────────────────────────────────────────────────────────────────────
# Stages 4 & 5 — verify and uninstall.
# ─────────────────────────────────────────────────────────────────────────────
@dataclass
class Verify:
    """How ``test`` validates an install.

    *args* is the argv passed to the installed binary (``None`` ⇒ existence
    check only).  When *contains* is set, success means the substring appears
    in stdout/stderr (the return code is ignored — for tools with idiosyncratic
    exit codes).  *path* overrides which file is probed (default: the first
    artifact's destination).
    """

    args: Optional[List[str]] = field(default_factory=lambda: ["--version"])
    contains: Optional[str] = None
    path: Optional[Dest] = None


@dataclass
class Remove:
    """How ``uninstall`` removes an install.

    Default (``tree=None``) unlinks every artifact's destination.  Set *tree*
    to ``rmtree`` a directory the install created instead (e.g. a conda prefix).
    """

    tree: Optional[Dest] = None


@dataclass
class Recipe:
    name: str
    artifacts: List[Artifact]
    verify: Verify = field(default_factory=Verify)
    remove: Remove = field(default_factory=Remove)


_VERSION_OVERRIDE_TOKENS = ("{version}", "{tag}")


def _has_version_override_token(text: Optional[str]) -> bool:
    return text is not None and any(token in text for token in _VERSION_OVERRIDE_TOKENS)


def supports_version_override(recipe: Recipe) -> bool:
    """Return True when a recipe can consume an explicit release tag."""
    return any(
        _has_version_override_token(art.url_template) or _has_version_override_token(art.member)
        for art in recipe.artifacts
    )


# ─────────────────────────────────────────────────────────────────────────────
# Engine — the five stages, implemented once.
# ─────────────────────────────────────────────────────────────────────────────
def _target_for(art: Artifact, key: str) -> Optional[str]:
    """Resolve the per-platform token, exiting 1 on an unsupported platform."""
    if art.targets is None:
        return None
    token = art.targets.get(key)
    if token is None:
        print(f"Unsupported platform: {key}", file=sys.stderr)
        sys.exit(1)
    return token


def _archive_for(art: Artifact, key: str) -> Archive:
    """Resolve the archive format, which may vary per platform."""
    archive = art.archive
    if isinstance(archive, dict):
        selected = archive.get(key)
        if selected is None:
            print(f"Unsupported platform: {key}", file=sys.stderr)
            sys.exit(1)
        return selected
    return archive


def _install_artifact(art: Artifact, env: EnvConfig, version_override: Optional[str] = None) -> Path:
    key = platform_key()
    target = _target_for(art, key)
    archive = _archive_for(art, key)
    tag, version = art.version.resolve_both(version_override)
    token = target if target is not None else ""
    url = art.url_template.format(target=token, version=version, tag=tag, ext=archive.ext)
    dest = art.dest.path(env)

    if art.action is not None:
        art.action.execute(url, dest, env)
        return dest

    if archive.kind is None:
        download_file(url, dest)
    else:
        tmp = download_to_tempdir(url, extract=archive.kind)
        try:
            member = (art.member or "").format(target=token, version=version, tag=tag, ext=archive.ext)
            src = tmp / member
            if not src.exists():
                print(f"Expected payload {member!r} not found in archive", file=sys.stderr)
                sys.exit(1)
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(src), str(dest))
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    if art.executable:
        dest.chmod(0o755)
    return dest


def _is_installed(recipe: Recipe, env: EnvConfig) -> bool:
    """Return True when every artifact destination already exists on disk."""
    for art in recipe.artifacts:
        dest = art.dest.path(env)
        if art.action is not None:
            # RunScript: installed when the update_marker exists inside the dest dir.
            if not (dest / art.action.update_marker).exists():
                return False
        else:
            if not dest.exists():
                return False
    return True


def install(
    recipe: Recipe,
    env: Optional[EnvConfig] = None,
    version_override: Optional[str] = None,
    force: bool = False,
) -> None:
    env = env or EnvConfig()
    if not force and _is_installed(recipe, env):
        print(f"{recipe.name} already installed; run 'update' to refresh")
        return
    for art in recipe.artifacts:
        dest = _install_artifact(art, env, version_override)
        print(f"Installed {recipe.name} → {dest}")


def uninstall(recipe: Recipe, env: Optional[EnvConfig] = None) -> None:
    env = env or EnvConfig()
    if recipe.remove.tree is not None:
        target = recipe.remove.tree.path(env)
        if target.exists():
            shutil.rmtree(target)
            print(f"Removed {target}")
        else:
            print(f"{target} not found", file=sys.stderr)
        return
    for art in recipe.artifacts:
        target = art.dest.path(env)
        if target.exists():
            target.unlink()
            print(f"Removed {target}")
        else:
            print(f"{target} not found", file=sys.stderr)


def _platform_constraints(art: Artifact) -> Optional[Set[str]]:
    keys: Optional[Set[str]] = set(art.targets) if art.targets is not None else None
    if isinstance(art.archive, dict):
        archive_keys = set(art.archive)
        keys = archive_keys if keys is None else keys & archive_keys
    return keys


def _supported_platforms(recipe: Recipe) -> Optional[Set[str]]:
    """Intersection of platform keys required by constrained artifacts.

    ``None`` means the recipe is platform-independent (never skipped by ``test``).
    """
    supported: Optional[Set[str]] = None
    for art in recipe.artifacts:
        constraints = _platform_constraints(art)
        if constraints is None:
            continue
        supported = set(constraints) if supported is None else supported & constraints
    return supported


def test_install(recipe: Recipe, env: Optional[EnvConfig] = None) -> int:
    """Validate an install on the current platform.

    Skips cleanly (exit 0) on an unsupported platform; fails (exit 1) when the
    expected file is missing on a supported platform.
    """
    env = env or EnvConfig()
    key = platform_key()
    supported = _supported_platforms(recipe)
    if supported is not None and key not in supported:
        print(f"Platform {key} unsupported by {recipe.name} installer; skipping", file=sys.stderr)
        return 0

    verify = recipe.verify
    probe_dest = verify.path if verify.path is not None else recipe.artifacts[0].dest
    probe = probe_dest.path(env)
    if not probe.exists():
        print(f"{probe} not found; run install first", file=sys.stderr)
        return 1

    if verify.args is None:
        print(f"{probe} found")
        return 0

    if verify.contains is not None:
        result = run(
            [str(probe), *verify.args],
            env=env.subprocess_env(),
            check=False,
            capture_output=True,
            text=True,
        )
        output = f"{result.stdout or ''}{result.stderr or ''}".strip()
        if verify.contains.lower() in output.lower():
            print(output)
            return 0
        print(
            f"{recipe.name} {' '.join(verify.args)} did not identify itself (rc={result.returncode}): {output!r}",
            file=sys.stderr,
        )
        return 1

    result = run([str(probe), *verify.args], env=env.subprocess_env(), check=False)
    return int(result.returncode)


def run_cli(recipe: Recipe) -> None:
    """Standard ``install`` / ``update`` / ``uninstall`` / ``test`` command-line dispatch."""
    parser = argparse.ArgumentParser(description=f"{recipe.name} installer")
    parser.add_argument(
        "action",
        choices=["install", "update", "reinstall", "uninstall", "test"],
        help=f"install: place {recipe.name} if not already present; "
        "update: force re-download/re-run even if already installed; "
        "reinstall: uninstall then install from scratch; "
        "uninstall: remove; test: validate (skips cleanly if platform unsupported)",
    )
    parser.add_argument(
        "--version",
        dest="version_override",
        metavar="TAG",
        default=None,
        help="git release tag to install (e.g. v1.2.3); default: latest",
    )
    args = parser.parse_args()
    if args.version_override is not None:
        if not supports_version_override(recipe):
            print(
                f"{recipe.name}: --version is not supported (no {{version}}/{{tag}} slot)",
                file=sys.stderr,
            )
            sys.exit(1)
    env = EnvConfig()
    if args.action == "install":
        install(recipe, env, args.version_override)
    elif args.action == "update":
        install(recipe, env, args.version_override, force=True)
    elif args.action == "reinstall":
        uninstall(recipe, env)
        install(recipe, env, args.version_override)
    elif args.action == "uninstall":
        uninstall(recipe, env)
    else:
        sys.exit(test_install(recipe, env))


# ─────────────────────────────────────────────────────────────────────────────
# Convenience constructor for the common case: one binary from a GitHub release.
# ─────────────────────────────────────────────────────────────────────────────
def _infer_archive(asset: str) -> Archive:
    if asset.endswith((".tar.gz", ".tgz", ".tar")):
        return TAR
    if asset.endswith(".zip"):
        return ZIP
    return RAW


def github_binary(
    name: str,
    repo: str,
    targets: Dict[str, str],
    asset: str,
    member: Optional[str] = None,
    version: Optional[VersionSpec] = None,
    dest: Optional[Dest] = None,
    executable: bool = True,
    verify: Optional[Verify] = None,
) -> Recipe:
    """Build a single-binary GitHub-release recipe.

    *repo* is ``owner/name``.  *asset* is the release asset filename (may
    contain ``{target}`` or ``{version}``); the archive format is inferred from
    its extension.  *member* is the path of the binary inside the archive (omit
    for a raw, un-archived asset).  *version* defaults to
    :class:`GitHubRedirect` (resolve the latest tag without the API).

    The download URL uses ``{tag}`` — the full git tag exactly as released —
    so it works for any tag format (``v1.2.3``, ``26.3.2-2``, ``rust-v0.135.0``)
    without any hardcoded prefix.  Use ``{version}`` in *asset* or *member*
    when the filename convention omits the leading ``v``.
    """
    if version is None:
        owner, _, repo_name = repo.partition("/")
        version = GitHubRedirect(owner, repo_name)
    archive = _infer_archive(asset)
    url_template = f"https://github.com/{repo}/releases/download/{{tag}}/{asset}"
    artifact = Artifact(
        url_template=url_template,
        dest=dest if dest is not None else Dest.bin(name),
        targets=targets,
        version=version,
        archive=archive,
        member=member,
        executable=executable,
    )
    return Recipe(name=name, artifacts=[artifact], verify=verify if verify is not None else Verify())

# --- pixi ---


RECIPE = github_binary(
    name="pixi",
    repo="prefix-dev/pixi",
    asset="pixi-{target}.tar.gz",
    member="pixi",
    targets={
        "Linux-x86_64": "x86_64-unknown-linux-musl",
        "Linux-aarch64": "aarch64-unknown-linux-musl",
        "Darwin-x86_64": "x86_64-apple-darwin",
        "Darwin-arm64": "aarch64-apple-darwin",
    },
    dest=Dest("pixi_home", "bin/pixi"),
)


if __name__ == "__main__":
    run_cli(RECIPE)
