#!/usr/bin/env python3
# Auto-generated by bsos compile system from bsos.installers.pixi — do not edit.
"""Pixi installer.

Downloads the latest pixi binary from GitHub releases and installs it to
``$PIXI_HOME/bin/pixi``."""

import argparse
import io
import os
import platform
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
import zipfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

# Baked from the bsos package at compile time.
__version__ = '0.1.0'

# --- _download ---


_USER_AGENT = f"bsos-installer/{__version__}"

PathLike = Union[str, Path]


def _open_url(url: str):
    req = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT})
    return urllib.request.urlopen(req)  # noqa: S310 — URL is from our own dispatch table


def _extract_tar(data: io.BytesIO, dest_dir: Path) -> None:
    with tarfile.open(fileobj=data, mode="r:*") as tar:
        # filter="data" (PEP 706) rejects absolute/parent paths and strips
        # unsafe mode bits (CVE-2007-4559). Fall back on Pythons that predate it.
        try:
            tar.extractall(dest_dir, filter="data")
        except TypeError:
            tar.extractall(dest_dir)


def download_and_extract_tar(url: str, dest_dir: PathLike) -> None:
    """Download a tar archive and extract into *dest_dir*."""
    dest_dir = Path(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)
    with _open_url(url) as resp:
        data = io.BytesIO(resp.read())
    _extract_tar(data, dest_dir)


def download_and_extract_zip(url: str, dest_dir: PathLike) -> None:
    """Download a zip archive and extract into *dest_dir*."""
    dest_dir = Path(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)
    with _open_url(url) as resp:
        data = io.BytesIO(resp.read())
    with zipfile.ZipFile(data) as zf:
        zf.extractall(dest_dir)


def download_to_tempdir(url: str, extract: str = "tar") -> Path:
    """Download and extract an archive into a fresh temp directory.

    Returns the temp directory path (caller is responsible for cleanup).
    *extract* is ``"tar"`` or ``"zip"``.
    """
    tmp = Path(tempfile.mkdtemp(prefix="bsos-"))
    if extract == "tar":
        download_and_extract_tar(url, tmp)
    elif extract == "zip":
        download_and_extract_zip(url, tmp)
    else:
        raise ValueError(f"Unknown extract format: {extract}")
    return tmp

# --- _env ---


# Inherited env vars that are safe/useful to pass to installer subprocesses.
_INHERIT_KEYS = (
    "HOME",
    "USER",
    "LOGNAME",
    "TERM",
    "PATH",
    "LANG",
    "LC_ALL",
    "TMPDIR",
    "SHELL",
    "SSH_AUTH_SOCK",
)


def detect_platform() -> Tuple[str, str]:
    """Detect OS and architecture, matching ``uname -sm`` output."""
    return platform.system(), platform.machine()


def platform_key() -> str:
    """Return ``<ostype>-<arch>`` for use in URL/archive dispatch tables."""
    ostype, arch = detect_platform()
    return f"{ostype}-{arch}"


class EnvConfig:
    """Compute envoy-managed paths, respecting pre-existing env vars.

    Path-like attributes are :class:`pathlib.Path`; the env-var mapping
    (:meth:`as_dict`) stringifies them.  An empty pre-existing value is
    treated as unset, matching the shell ``${VAR:-default}`` semantics.
    """

    def __init__(self, environ: Optional[Dict[str, str]] = None) -> None:
        env = dict(environ) if environ is not None else dict(os.environ)

        self.ostype, self.arch = detect_platform()
        self.home = Path(env.get("HOME") or Path.home())

        appdir = env.get("__APPDIR", "")
        self.local_root = Path(
            env.get("__LOCAL_ROOT")
            or (f"{appdir}/local" if appdir else self.home / ".local")
        )
        self.opt_root = Path(
            env.get("__OPT_ROOT") or self.local_root / "opt" / f"{self.ostype}-{self.arch}"
        )

        self.mamba_root_prefix = Path(env.get("MAMBA_ROOT_PREFIX") or self.opt_root / "miniforge3")
        self.pixi_home = Path(env.get("PIXI_HOME") or self.opt_root / "pixi")
        self.zim_home = Path(env.get("ZIM_HOME") or self.home / ".zim")

        self.xdg_config_home = Path(env.get("XDG_CONFIG_HOME") or self.home / ".config")
        self.xdg_data_home = Path(env.get("XDG_DATA_HOME") or self.local_root / "share")
        self.xdg_state_home = Path(env.get("XDG_STATE_HOME") or self.local_root / "state")
        self.xdg_cache_home = Path(env.get("XDG_CACHE_HOME") or self.home / ".cache")

        self.bin_dir = self.opt_root / "bin"

    def as_dict(self) -> Dict[str, str]:
        """All envoy-managed vars as a flat ``str``-valued dict."""
        return {
            "__OSTYPE": self.ostype,
            "__ARCH": self.arch,
            "__LOCAL_ROOT": str(self.local_root),
            "__OPT_ROOT": str(self.opt_root),
            "MAMBA_ROOT_PREFIX": str(self.mamba_root_prefix),
            "PIXI_HOME": str(self.pixi_home),
            "ZIM_HOME": str(self.zim_home),
            "XDG_CONFIG_HOME": str(self.xdg_config_home),
            "XDG_DATA_HOME": str(self.xdg_data_home),
            "XDG_STATE_HOME": str(self.xdg_state_home),
            "XDG_CACHE_HOME": str(self.xdg_cache_home),
        }

    def subprocess_env(self) -> Dict[str, str]:
        """Controlled environment for installer subprocesses.

        A minimal base of inherited vars plus all envoy-managed vars, so
        child processes don't inherit unrelated env state.
        """
        env = {key: os.environ[key] for key in _INHERIT_KEYS if key in os.environ}
        env.update(self.as_dict())
        return env


# --- _subprocess ---


def run(
    cmd: List[str],
    env: Optional[Dict[str, str]] = None,
    check: bool = True,
    **kwargs: object,
) -> "subprocess.CompletedProcess":
    """Run *cmd* with an explicit environment.

    Pass *env* from :meth:`EnvConfig.subprocess_env` to isolate the child
    from the caller's full environment.  *check* defaults to ``True``;
    pass ``check=False`` when the caller wants to inspect ``returncode``.
    """
    return subprocess.run(cmd, env=env, check=check, **kwargs)

# --- pixi ---


_TARGETS = {
    "Linux-x86_64": "x86_64-unknown-linux-musl",
    "Linux-aarch64": "aarch64-unknown-linux-musl",
    "Darwin-x86_64": "x86_64-apple-darwin",
    "Darwin-arm64": "aarch64-apple-darwin",
}

# Use the /releases/latest/download/ redirect — no GitHub API call, no rate limit.
_URL_TEMPLATE = "https://github.com/prefix-dev/pixi/releases/latest/download/pixi-{target}.tar.gz"


def install(env: Optional[EnvConfig] = None) -> None:
    env = env or EnvConfig()
    key = platform_key()
    target = _TARGETS.get(key)
    if target is None:
        print(f"Unsupported platform: {key}", file=sys.stderr)
        sys.exit(1)

    url = _URL_TEMPLATE.format(target=target)
    tmp = download_to_tempdir(url, extract="tar")
    try:
        src = tmp / "pixi"
        if not src.exists():
            print("Expected 'pixi' binary not found in archive", file=sys.stderr)
            sys.exit(1)
        pixi_bin_dir = env.pixi_home / "bin"
        pixi_bin_dir.mkdir(parents=True, exist_ok=True)
        dest = pixi_bin_dir / "pixi"
        shutil.move(str(src), str(dest))
        dest.chmod(0o755)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print(f"Installed pixi (latest) to {dest}")


def uninstall(env: Optional[EnvConfig] = None) -> None:
    env = env or EnvConfig()
    target = env.pixi_home / "bin" / "pixi"
    if target.exists():
        target.unlink()
        print(f"Removed {target}")
    else:
        print(f"{target} not found", file=sys.stderr)


def test_install(env: Optional[EnvConfig] = None) -> int:
    """Validate the pixi install on the current platform.

    Skips cleanly (exit 0) on unsupported platforms.
    """
    env = env or EnvConfig()
    key = platform_key()
    if key not in _TARGETS:
        print(f"Platform {key} unsupported by pixi installer; skipping", file=sys.stderr)
        return 0
    pixi_bin = env.pixi_home / "bin" / "pixi"
    if not pixi_bin.exists():
        print(f"{pixi_bin} not found; run install first", file=sys.stderr)
        return 1
    result = run([str(pixi_bin), "--version"], env=env.subprocess_env(), check=False)
    return result.returncode


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "action",
        choices=["install", "uninstall", "test"],
        help="install/uninstall pixi, or test validates an install "
        "(skips cleanly if the platform is unsupported)",
    )
    args = parser.parse_args()
    env = EnvConfig()
    if args.action == "install":
        install(env)
    elif args.action == "uninstall":
        uninstall(env)
    else:
        sys.exit(test_install(env))


if __name__ == "__main__":
    main()
