#!/usr/bin/env python3
# Auto-generated by bsos compile system from bsos.installers.sman — do not edit.
"""sman snippet manager installer.

Installs the ``sman`` binary and its shell-integration file ``sman.rc``.  The
sman-snippets repository is managed separately (clone it to
``$XDG_DATA_HOME/sman/snippets`` via git)."""

from __future__ import annotations

import argparse
import io
import os
import platform
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple, Union

# Baked from the bsos package at compile time.
__version__ = '0.1.0'

# --- _download ---


_USER_AGENT = f"bsos-installer/{__version__}"


def _open_url(url: str):
    req = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT})
    return urllib.request.urlopen(req)  # noqa: S310 — URL is from our own dispatch table


def _extract_tar(data: io.BytesIO, dest_dir: Path) -> None:
    with tarfile.open(fileobj=data, mode="r:*") as tar:
        # filter="data" (PEP 706) rejects absolute/parent paths and strips
        # unsafe mode bits (CVE-2007-4559). Fall back on Pythons that predate it.
        try:
            tar.extractall(dest_dir, filter="data")
        except TypeError:
            tar.extractall(dest_dir)


def download_file(url: str, dest: PathLike) -> None:
    """Download *url* to a local file at *dest*."""
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    with _open_url(url) as resp, dest.open("wb") as f:
        shutil.copyfileobj(resp, f)


def download_and_extract_tar(url: str, dest_dir: PathLike) -> None:
    """Download a tar archive and extract into *dest_dir*."""
    dest_dir = Path(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)
    with _open_url(url) as resp:
        data = io.BytesIO(resp.read())
    _extract_tar(data, dest_dir)


def download_and_extract_zip(url: str, dest_dir: PathLike) -> None:
    """Download a zip archive and extract into *dest_dir*."""
    dest_dir = Path(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)
    with _open_url(url) as resp:
        data = io.BytesIO(resp.read())
    with zipfile.ZipFile(data) as zf:
        zf.extractall(dest_dir)


def resolve_latest_github_tag(owner: str, repo: str) -> str:
    """Return the latest release tag for a GitHub repo without calling the GitHub API.

    Follows the /releases/latest redirect URL; the final URL ends with /tag/<tagname>.
    Avoids the GitHub API (60 req/hour unauthenticated limit).
    """
    url = f"https://github.com/{owner}/{repo}/releases/latest"
    with _open_url(url) as resp:
        final_url = resp.url
    tag = final_url.rstrip("/").split("/")[-1]
    if not tag or tag in {"latest", "releases"}:
        raise RuntimeError(f"Could not resolve latest release tag for {owner}/{repo}")
    return tag


def download_to_tempdir(url: str, extract: str = "tar") -> Path:
    """Download and extract an archive into a fresh temp directory.

    Returns the temp directory path (caller is responsible for cleanup).
    *extract* is ``"tar"`` or ``"zip"``.
    """
    tmp = Path(tempfile.mkdtemp(prefix="bsos-"))
    if extract == "tar":
        download_and_extract_tar(url, tmp)
    elif extract == "zip":
        download_and_extract_zip(url, tmp)
    else:
        raise ValueError(f"Unknown extract format: {extract}")
    return tmp

# --- _env ---


# Inherited env vars that are safe/useful to pass to installer subprocesses.
_INHERIT_KEYS = (
    "HOME",
    "USER",
    "LOGNAME",
    "TERM",
    "PATH",
    "LANG",
    "LC_ALL",
    "TMPDIR",
    "SHELL",
    "SSH_AUTH_SOCK",
)


def detect_platform() -> Tuple[str, str]:
    """Detect OS and architecture, matching ``uname -sm`` output."""
    return platform.system(), platform.machine()


def platform_key() -> str:
    """Return ``<ostype>-<arch>`` for use in URL/archive dispatch tables."""
    ostype, arch = detect_platform()
    return f"{ostype}-{arch}"


class EnvConfig:
    """Compute envoy-managed paths, respecting pre-existing env vars.

    Path-like attributes are :class:`pathlib.Path`; the env-var mapping
    (:meth:`as_dict`) stringifies them.  An empty pre-existing value is
    treated as unset, matching the shell ``${VAR:-default}`` semantics.
    """

    def __init__(self, environ: Optional[Dict[str, str]] = None) -> None:
        env = dict(environ) if environ is not None else dict(os.environ)

        self.ostype, self.arch = detect_platform()
        self.home = Path(env.get("HOME") or Path.home())

        appdir = env.get("__APPDIR", "")
        self.local_root = Path(
            env.get("__LOCAL_ROOT")
            or (f"{appdir}/local" if appdir else self.home / ".local")
        )
        self.opt_root = Path(
            env.get("__OPT_ROOT") or self.local_root / "opt" / f"{self.ostype}-{self.arch}"
        )

        self.mamba_root_prefix = Path(env.get("MAMBA_ROOT_PREFIX") or self.opt_root / "miniforge3")
        self.pixi_home = Path(env.get("PIXI_HOME") or self.opt_root / "pixi")
        self.zim_home = Path(env.get("ZIM_HOME") or self.home / ".zim")

        self.xdg_config_home = Path(env.get("XDG_CONFIG_HOME") or self.home / ".config")
        self.xdg_data_home = Path(env.get("XDG_DATA_HOME") or self.local_root / "share")
        self.xdg_state_home = Path(env.get("XDG_STATE_HOME") or self.local_root / "state")
        self.xdg_cache_home = Path(env.get("XDG_CACHE_HOME") or self.home / ".cache")

        self.bin_dir = self.opt_root / "bin"

    def as_dict(self) -> Dict[str, str]:
        """All envoy-managed vars as a flat ``str``-valued dict."""
        return {
            "__OSTYPE": self.ostype,
            "__ARCH": self.arch,
            "__LOCAL_ROOT": str(self.local_root),
            "__OPT_ROOT": str(self.opt_root),
            "MAMBA_ROOT_PREFIX": str(self.mamba_root_prefix),
            "PIXI_HOME": str(self.pixi_home),
            "ZIM_HOME": str(self.zim_home),
            "XDG_CONFIG_HOME": str(self.xdg_config_home),
            "XDG_DATA_HOME": str(self.xdg_data_home),
            "XDG_STATE_HOME": str(self.xdg_state_home),
            "XDG_CACHE_HOME": str(self.xdg_cache_home),
        }

    def subprocess_env(self) -> Dict[str, str]:
        """Controlled environment for installer subprocesses.

        A minimal base of inherited vars plus all envoy-managed vars, so
        child processes don't inherit unrelated env state.
        """
        env = {key: os.environ[key] for key in _INHERIT_KEYS if key in os.environ}
        env.update(self.as_dict())
        return env


# --- _subprocess ---


def run(
    cmd: List[str],
    env: Optional[Dict[str, str]] = None,
    check: bool = True,
    **kwargs: object,
) -> "subprocess.CompletedProcess":
    """Run *cmd* with an explicit environment.

    Pass *env* from :meth:`EnvConfig.subprocess_env` to isolate the child
    from the caller's full environment.  *check* defaults to ``True``;
    pass ``check=False`` when the caller wants to inspect ``returncode``.
    """
    return subprocess.run(cmd, env=env, check=check, **kwargs)

# --- _recipe ---


# ─────────────────────────────────────────────────────────────────────────────
# Stage 1 — version: how to fill ``{version}`` in a download URL.
# ─────────────────────────────────────────────────────────────────────────────
class VersionSpec:
    """Strategy for resolving the ``{version}`` token of a download URL."""

    def resolve(self, override: Optional[str] = None) -> str:
        raise NotImplementedError


@dataclass
class Latest(VersionSpec):
    """No version lookup — the URL uses the ``/releases/latest/download/`` redirect.

    Only for non-GitHub-releases URLs that have no ``{version}`` slot.  The
    ``--version`` flag is rejected at the ``run_cli`` level before this is reached.
    """

    def resolve(self, override: Optional[str] = None) -> str:
        return "latest"


@dataclass
class GitHubRedirect(VersionSpec):
    """Resolve the latest release tag via the ``/releases/latest`` redirect.

    Never calls the GitHub API (rate-limited at 60 req/hour unauthenticated).
    Set *strip_v* to drop a leading ``v`` from the tag — use this when the URL
    template hardcodes ``v{version}`` in the download path (the common GitHub
    convention).  Leave *strip_v* False for repos whose tags have no ``v``
    prefix (e.g. ``conda-forge/miniforge`` tags like ``26.3.2-2``).

    ``--version`` overrides the auto-resolved tag; *strip_v* is applied to the
    override identically to the resolved tag.
    """

    owner: str
    repo: str
    strip_v: bool = False

    def resolve(self, override: Optional[str] = None) -> str:
        tag = override if override is not None else resolve_latest_github_tag(self.owner, self.repo)
        return tag.lstrip("v") if self.strip_v else tag


# ─────────────────────────────────────────────────────────────────────────────
# Stage 2 — archive kind and destination.
# ─────────────────────────────────────────────────────────────────────────────
@dataclass(frozen=True)
class Archive:
    """An archive format: its filename extension and its extractor kind.

    Frozen (immutable, hashable) so the ``RAW`` constant is usable as the
    ``Artifact.archive`` field default — these are shared value constants.
    """

    ext: str
    kind: Optional[str]  # "tar" | "zip" | None (raw, not an archive)


TAR = Archive("tar.gz", "tar")
RAW = Archive("", None)


@dataclass
class Dest:
    """A destination: an :class:`EnvConfig` directory attribute plus a relative path."""

    area: str  # an EnvConfig attribute name, e.g. "bin_dir", "pixi_home"
    rel: str = ""

    def path(self, env: EnvConfig) -> Path:
        base: Path = getattr(env, self.area)
        return base / self.rel if self.rel else base

    @classmethod
    def bin(cls, name: str) -> "Dest":
        """Shorthand for ``$__OPT_ROOT/bin/<name>``."""
        return cls("bin_dir", name)


@dataclass
class Artifact:
    """One download that results in one placed file (or one run script).

    ``url_template`` may reference ``{target}`` (the per-platform token),
    ``{version}`` and ``{ext}`` (the resolved archive extension).  ``member``
    is the path of the wanted file *inside* the extracted archive (templated
    the same way); ``None`` means the download itself is the file.
    """

    url_template: str
    dest: Dest
    targets: Optional[Dict[str, str]] = None  # platform_key -> token; None = platform-independent
    version: VersionSpec = field(default_factory=Latest)
    archive: Union[Archive, Dict[str, Archive]] = RAW  # scalar, or per-platform mapping
    member: Optional[str] = None
    executable: bool = True
    action: Optional["RunScript"] = None  # forward ref keeps RunScript out of place-only scripts


# ─────────────────────────────────────────────────────────────────────────────
# Stages 4 & 5 — verify and uninstall.
# ─────────────────────────────────────────────────────────────────────────────
@dataclass
class Verify:
    """How ``test`` validates an install.

    *args* is the argv passed to the installed binary (``None`` ⇒ existence
    check only).  When *contains* is set, success means the substring appears
    in stdout/stderr (the return code is ignored — for tools with idiosyncratic
    exit codes).  *path* overrides which file is probed (default: the first
    artifact's destination).
    """

    args: Optional[List[str]] = field(default_factory=lambda: ["--version"])
    contains: Optional[str] = None
    path: Optional[Dest] = None


@dataclass
class Remove:
    """How ``uninstall`` removes an install.

    Default (``tree=None``) unlinks every artifact's destination.  Set *tree*
    to ``rmtree`` a directory the install created instead (e.g. a conda prefix).
    """

    tree: Optional[Dest] = None


@dataclass
class Recipe:
    name: str
    artifacts: List[Artifact]
    verify: Verify = field(default_factory=Verify)
    remove: Remove = field(default_factory=Remove)


# ─────────────────────────────────────────────────────────────────────────────
# Engine — the five stages, implemented once.
# ─────────────────────────────────────────────────────────────────────────────
def _target_for(art: Artifact, key: str) -> Optional[str]:
    """Resolve the per-platform token, exiting 1 on an unsupported platform."""
    if art.targets is None:
        return None
    token = art.targets.get(key)
    if token is None:
        print(f"Unsupported platform: {key}", file=sys.stderr)
        sys.exit(1)
    return token


def _archive_for(art: Artifact, key: str) -> Archive:
    """Resolve the archive format, which may vary per platform."""
    archive = art.archive
    if isinstance(archive, dict):
        selected = archive.get(key)
        if selected is None:
            print(f"Unsupported platform: {key}", file=sys.stderr)
            sys.exit(1)
        return selected
    return archive


def _install_artifact(art: Artifact, env: EnvConfig, version_override: Optional[str] = None) -> Path:
    key = platform_key()
    target = _target_for(art, key)
    archive = _archive_for(art, key)
    version = art.version.resolve(version_override)
    token = target if target is not None else ""
    url = art.url_template.format(target=token, version=version, ext=archive.ext)
    dest = art.dest.path(env)

    if art.action is not None:
        art.action.execute(url, dest, env)
        return dest

    if archive.kind is None:
        download_file(url, dest)
    else:
        tmp = download_to_tempdir(url, extract=archive.kind)
        try:
            member = (art.member or "").format(target=token, version=version, ext=archive.ext)
            src = tmp / member
            if not src.exists():
                print(f"Expected payload {member!r} not found in archive", file=sys.stderr)
                sys.exit(1)
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(src), str(dest))
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    if art.executable:
        dest.chmod(0o755)
    return dest


def install(recipe: Recipe, env: Optional[EnvConfig] = None, version_override: Optional[str] = None) -> None:
    env = env or EnvConfig()
    for art in recipe.artifacts:
        dest = _install_artifact(art, env, version_override)
        print(f"Installed {recipe.name} → {dest}")


def uninstall(recipe: Recipe, env: Optional[EnvConfig] = None) -> None:
    env = env or EnvConfig()
    if recipe.remove.tree is not None:
        target = recipe.remove.tree.path(env)
        if target.exists():
            shutil.rmtree(target)
            print(f"Removed {target}")
        else:
            print(f"{target} not found", file=sys.stderr)
        return
    for art in recipe.artifacts:
        target = art.dest.path(env)
        if target.exists():
            target.unlink()
            print(f"Removed {target}")
        else:
            print(f"{target} not found", file=sys.stderr)


def _supported_platforms(recipe: Recipe) -> Optional[Set[str]]:
    """Union of platform keys across platform-specific artifacts.

    ``None`` means the recipe is platform-independent (never skipped by ``test``).
    """
    keys: Set[str] = set()
    specific = False
    for art in recipe.artifacts:
        if art.targets is not None:
            specific = True
            keys.update(art.targets)
    return keys if specific else None


def test_install(recipe: Recipe, env: Optional[EnvConfig] = None) -> int:
    """Validate an install on the current platform.

    Skips cleanly (exit 0) on an unsupported platform; fails (exit 1) when the
    expected file is missing on a supported platform.
    """
    env = env or EnvConfig()
    key = platform_key()
    supported = _supported_platforms(recipe)
    if supported is not None and key not in supported:
        print(f"Platform {key} unsupported by {recipe.name} installer; skipping", file=sys.stderr)
        return 0

    verify = recipe.verify
    probe_dest = verify.path if verify.path is not None else recipe.artifacts[0].dest
    probe = probe_dest.path(env)
    if not probe.exists():
        print(f"{probe} not found; run install first", file=sys.stderr)
        return 1

    if verify.args is None:
        print(f"{probe} found")
        return 0

    if verify.contains is not None:
        result = run(
            [str(probe), *verify.args],
            env=env.subprocess_env(),
            check=False,
            capture_output=True,
            text=True,
        )
        output = f"{result.stdout or ''}{result.stderr or ''}".strip()
        if verify.contains.lower() in output.lower():
            print(output)
            return 0
        print(
            f"{recipe.name} {' '.join(verify.args)} did not identify itself (rc={result.returncode}): {output!r}",
            file=sys.stderr,
        )
        return 1

    result = run([str(probe), *verify.args], env=env.subprocess_env(), check=False)
    return int(result.returncode)


def run_cli(recipe: Recipe) -> None:
    """Standard ``install`` / ``uninstall`` / ``test`` command-line dispatch."""
    parser = argparse.ArgumentParser(description=f"{recipe.name} installer")
    parser.add_argument(
        "action",
        choices=["install", "uninstall", "test"],
        help=f"install/uninstall {recipe.name}, or test validates an install "
        "(skips cleanly if the platform is unsupported)",
    )
    parser.add_argument(
        "--version",
        dest="version_override",
        metavar="TAG",
        default=None,
        help="git release tag to install (e.g. v1.2.3); default: latest",
    )
    args = parser.parse_args()
    if args.version_override is not None:
        has_slot = any("{version}" in a.url_template for a in recipe.artifacts)
        if not has_slot:
            print(
                f"{recipe.name}: --version is not supported (no {{version}} slot in URL)",
                file=sys.stderr,
            )
            sys.exit(1)
    env = EnvConfig()
    if args.action == "install":
        install(recipe, env, args.version_override)
    elif args.action == "uninstall":
        uninstall(recipe, env)
    else:
        sys.exit(test_install(recipe, env))


# ─────────────────────────────────────────────────────────────────────────────
# Convenience constructor for the common case: one binary from a GitHub release.
# ─────────────────────────────────────────────────────────────────────────────


# --- sman ---


RECIPE = Recipe(
    name="sman",
    artifacts=[
        Artifact(
            url_template="https://github.com/ickc/sman/releases/download/v{version}/sman-{target}-v{version}.tgz",
            version=GitHubRedirect("ickc", "sman", strip_v=True),
            archive=TAR,
            targets={
                "Darwin-arm64": "darwin-arm64",
                "Darwin-x86_64": "darwin-amd64",
                "Linux-x86_64": "linux-amd64",
                "Linux-aarch64": "linux-arm64",
                "Linux-ppc64le": "linux-ppc64le",
                "FreeBSD-amd64": "freebsd-amd64",
            },
            member="sman-{target}-v{version}",
            dest=Dest.bin("sman"),
        ),
        Artifact(
            url_template="https://raw.githubusercontent.com/ickc/sman/refs/heads/main/sman.rc",
            archive=RAW,
            dest=Dest("xdg_data_home", "sman/sman.rc"),
            executable=False,
        ),
    ],
    verify=Verify(args=["-h"]),
)


if __name__ == "__main__":
    run_cli(RECIPE)
