name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.9
        pandoc-version:
          - latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-environment: true
        create-args: >-
          python=${{ matrix.python-version }}
        environment-file: environment.yml
    - name: Install dependencies—pip
      run: |
        make editable
        name=bsos; python -m ipykernel install --user --name "$name" --display-name "$name"
    - name: Install dependencies—pandoc
    - uses: nikeee/setup-pandoc@v1
      with:
        pandoc-version: ${{ matrix.pandoc-version }}
    - name: Make docs
      run: make docs -B
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/docs
