name: Python package

on: [push, pull_request]

jobs:
  build-n-publish:

    runs-on: ubuntu-latest
    # required by conda
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        # see setup.py for supported versions
        # here instead of having a matrix
        # we only test combinations in a round-robin fashion
        # make sure the versions are monotmonic increasing w.r.t. each other
        # other wise e.g. an older version of a dependency may not work well with a newer version of Python
        include:
          - python-version: "3.8"
            pandoc-version: "2.15"
          - python-version: "3.9"
            pandoc-version: "2.16"
          - python-version: "3.10"
            pandoc-version: "latest"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-environment: true
        create-args: >-
          python=${{ matrix.python-version }}
        environment-file: environment.yml
    - name: Install dependencies—pip
      run: |
        # let coverage read setup.py instead of pyproject.toml
        make editable
    - name: Install dependencies—pandoc
    - uses: nikeee/setup-pandoc@v1
      with:
        pandoc-version: ${{ matrix.pandoc-version }}
    - name: Sanity check
      run: |
        pip check
        python -c 'import bsos'
    - name: Tests
      run: |
        make test COVHTML='--cov-report=xml'
